### ISSUE TITLE
Install for all users

### ISSUE THREAD

**Issue by button04** [ubergrape/grape-electron#155]
Hello!

I need to deploy grape-electron silent for all users on a windows 10 desktop. 

I tried msiexec /i Grape-3.4.0.msi allusers=1 /qn in many variations but nothing worked.

Is there anywhere a guide how to use silent parameters?

Thanks,
Cheers

**Comment by AleshaOleg** [comment]
Please use `.exe` as `.msi` missing some features like auto-updates and choose a user group to install the app.

I answered how to do that here - https://github.com/ubergrape/grape-electron/issues/156
