### ISSUE TITLE
Silent installation

### ISSUE THREAD

**Issue by button04** [ubergrape/grape-electron#156]
The switch **"Grape Setup 3.x.x.exe" /S /allusers** doesn´t work. Can anybody fix that? Please

**Comment by AleshaOleg** [comment]
It's working.

1) Press the Windows button
2) Type "cmd"
3) Right-click and choose "Run as administrator"
4) Choose a folder where the installer located with `cd` command
5) `Grape-Setup-3.5.0.exe /S /allusers`
