### ISSUE TITLE
Windows Client 2.13 doesn't start

### ISSUE THREAD

**Issue by felixtosh** [ubergrape/grape-electron#31]
@sk7 commented on [Tue Jun 06 2017](https://github.com/ubergrape/grape-web-client/issues/465)

#### Step to reproduce

according to customer:

1. have 2.12 installed on windows
2. update to 2.13
3. reboot pc

**note:** this is the same customer that has the virus scan problems, so if it is not reproducible, we should try with their virus scanner, see #404 

#### result

Grape does not start

### operating system

according to customer: happens on windows 10
blerta also tested on windows 7, also fails, see comments

#### customer emails

email 1
```
ich hab letzte woche einige von grape 2.10 auf 2.12 upgegraded und die kommen heute alle mit dem fehler daher

Faulting application name: Grape.exe, version: 1.4.14.0, time stamp: 0x58753971 
Faulting module name: Grape.exe, version: 1.4.14.0, time stamp: 0x58753971 
Exception code: 0x80000003 
Fault offset: 0x00266399 
Faulting process id: 0x10c4 
Faulting application start time: 0x01d2de9d43eca18c 
Faulting application path: C:\Program Files (x86)\Grape\Grape.exe 
Faulting module path: C:\Program Files (x86)\Grape\Grape.exe 
Report Id: e0d0637e-ce46-4bbc-b087-7084172fb88b 
Faulting package full name: 
Faulting package-relative application ID:

Grape lässt sich dabei auch nicht mehr starten. Uninstall und install 2.13, dann gehts wieder...
```

email 2

```
Andere kiste, hab 2.13 auf eine 2.12 version im betrieb drüberinstalliert.

Nach einem reboot folgender fehler und grape startet jetzt nicht mehr....

[8352] onecore\windows\feedback\core\wercommon\libex\usertokenutility.cpp(755)\wer.dll!6CFD282B: (caller: 6CFD0892) LogHr(1) tid(1f48) 80070005 Access is denied. 
[8352]     Msg:[No session users available.] 
[8352] onecore\windows\feedback\core\wercommon\libex\usertokenutility.cpp(755)\wer.dll!6CFD282B: (caller: 6CFD0892) LogHr(2) tid(1f48) 80070005 Access is denied. 
[8352]     Msg:[No session users available.] 
[8352] onecore\windows\feedback\core\wercommon\libex\usertokenutility.cpp(755)\wer.dll!6CFD282B: (caller: 6CFD0892) LogHr(3) tid(1f48) 80070005 Access is denied. 
[8352]     Msg:[No session users available.] 
[8352] onecore\windows\feedback\core\wercommon\libex\usertokenutility.cpp(755)\wer.dll!6CFD282B: (caller: 6CFD0892) LogHr(4) tid(2f24) 80070005 Access is denied. 
[8352]     Msg:[No session users available.] 
[8352] onecore\windows\feedback\core\wercommon\libex\usertokenutility.cpp(755)\wer.dll!6CFD282B: (caller: 6CFD0892) LogHr(5) tid(1f48) 80070005 Access is denied. 
[8352]     Msg:[No session users available.] 
[8352] onecore\windows\feedback\core\wercommon\libex\usertokenutility.cpp(755)\wer.dll!6CFD282B: (caller: 6CFD0892) LogHr(6) tid(1f48) 80070005 Access is denied. 
[8352]     Msg:[No session users available.]

und in der command line: 
[7340:0606/142732:FATAL:icu_util.cc(292)] Check failed: result.
Backtrace:
       (No symbol) [0x012FA417]
       (No symbol) [0x012F4F51]
       GetHandleVerifier [0x0138714C+378876]
       icu_56::BreakIterator::isBufferClone [0x01472546+408710]
       icu_56::BreakIterator::isBufferClone [0x01470C96+402390]
       (No symbol) [0x01152572]
       icu_56::Transliterator::setID [0x0376A545+261989]
       BaseThreadInitThunk [0x76DB8744+36]
       RtlGetAppContainerNamedObjectPath [0x76F4587D+253]
       RtlGetAppContainerNamedObjectPath [0x76F4584D+205]

```

#### Browser and OS version

Electron desktop app 2.13 (pre-release), windows 7 or 10 (?)

---

@kof commented on [Tue Jun 06 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-306473996)

Windows version might be important in such cases.

---

@sk7 commented on [Tue Jun 06 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-306480064)

windows 10 confirmed

> ja alles win 10. Teils mit creators update 1703... müsste ich genau nachsehen falls das eine rolle spielt.....

---

@BlertaZeka commented on [Tue Jun 06 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-306492452)

tested on win7. after reboot if i try to open grape app this appears (grape doesnt open):

![screen shot 2017-06-06 at 15 48 03](https://cloud.githubusercontent.com/assets/26742647/26832496/f4a20d6c-4acf-11e7-8daa-915569c44e6b.png)

---

@BlertaZeka commented on [Wed Jun 07 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-306775294)

tested on win10, grape does not start. only starts after restarting the pc
installing 2.13 works without a problem if there is no 2.12 on the pc

---

@sk7 commented on [Thu Jun 08 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-307079390)

does this bug also happen to 2.12 or only 2.13? this is important because 2.12 is supposed to be the last stable version (2.13 is a pre-release)

---

@kof commented on [Fri Jun 09 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-307338281)

We have 2 emails now which claim different things

1st: upgrade from 2.10 to 2.12 
2nd: upgrade from 2.12 to 2.13

Also the first guy says that 2.13 works.

---

@kof commented on [Fri Jun 09 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-307352350)

Can't reproduce, @BlertaZeka please describe exactly what you did, every step.

---

@BlertaZeka commented on [Mon Jun 12 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-307746059)

This is what i reproduced now 

#### my steps on win10:
1. install 2.12 (because i didn't have it on my laptop)
after installing launching grape works fine

2. dowload 2.13 msi  and install 

this appears, following these steps:
![image](https://user-images.githubusercontent.com/26742647/27029033-fac81696-4f66-11e7-8ce7-dba14e871092.png)

![image](https://user-images.githubusercontent.com/26742647/27029036-fd91e492-4f66-11e7-90e8-7a0dd3185471.png)

![image](https://user-images.githubusercontent.com/26742647/27029042-00930162-4f67-11e7-8455-4cc1ad37b727.png)

![image](https://user-images.githubusercontent.com/26742647/27029048-03701fe6-4f67-11e7-8757-88e2dcd75040.png)

![image](https://user-images.githubusercontent.com/26742647/27029054-0734c668-4f67-11e7-9f56-626592ff2536.png)

3. "restart now", try to open grape app
it does not open

4. restart
opening grape still doesnt work

5. uninstall 2.13

6. reinstall 2.13

7. no problem opening app

---

@kof commented on [Tue Jun 13 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-308138433)

Ok I got it reproduced on win 7. It happens when you don't close the service in tray icon before installing the new version. I think this problem is not new, it existed in every previous version.

---

@kof commented on [Tue Jun 13 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-308138515)

Maybe @dershodan has an idea?

---

@kof commented on [Tue Jun 13 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-308142447)

Maybe the actual prob is that windows is not able to exit the current processes when installing a new version?

---

@dershodan commented on [Thu Jun 22 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-310411451)

I suggest 2 possible solutions:

1. modify the `InstallExecuteSequence` to this:
```
<InstallExecuteSequence>
    <RemoveExistingProducts After="InstallValidate"/>
    <InstallInitialize After="RemoveExistingProducts"/>
</InstallExecuteSequence>
```

2. Use [MajorUpgrade](http://wixtoolset.org/documentation/manual/v3/howtos/updates/major_upgrade.html) rather than Upgrade (provided our wix version is new enough.

---

@kof commented on [Fri Jun 23 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-310662392)

      <InstallInitialize After="RemoveExistingProducts"/>

Doesn't exist with After attribute

---

@sk7 commented on [Mon Jul 10 2017](https://github.com/ubergrape/grape-web-client/issues/465#issuecomment-314088891)

Christoph can't do it. @thorstenjung could look into that

**Comment by nikgraf** [comment]
Outdate issue
