### ISSUE TITLE
alpha version 3.0.0 alpha 12 does not support custom site instances

### ISSUE THREAD

**Issue by msperl** [ubergrape/grape-electron#79]
alpha version 3.0.0 alpha 12 does not support custom site instances
only login to the cloud version seems supported

**Comment by AleshaOleg** [comment]
@msperl sorry, marked 3.0.0-alpha.12 as the latest release for test purposes. Please use latest stable version - https://github.com/ubergrape/grape-electron/releases/tag/2.19.0
